[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
index-url = "https://pypi.org/simple"
[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[project]
name = "rl-baselines"
version = "0.0.1"
description = "Implementations of Reinforcement Learning algorithms as baselines in Pytorch"
readme = "Readme.md"
authors = [
    { name = "Erick T", email = "erickdeivy01@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.12"
dependencies = [
    "omegaconf==2.3.0",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "torchaudio==2.6.0",
    "lightning==2.6.0",
    "tensordict==0.10.0",
    "gymnasium[classic-control]==1.2.2",
    "torchrl==0.10.1",
    "opencv-python==4.12.0.88",
    "tensorboardX==2.6.4",
    "tensorboard==2.20.0",
    "ale-py==0.11.2"
]

[project.optional-dependencies]
runtime = [

]
dev = [
    "ruff>=0.1.6",
    "mypy>=1.7.0",
    "types-PyYAML>=6.0.0",
    "pre-commit>=3.6.0",
    "ipython>=8.17.0",
    "ipdb>=0.13.13",
]
docs = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.4.0",
    "mkdocstrings[python]>=0.24.0",
]

[project.urls]
Homepage = "https://github.com/erickTornero/rl-baselines"
Documentation = "https://github.com/erickTornero/rl-baselines"
Repository = "https://github.com/erickTornero/rl-baselines"
Issues = "https://github.com/erickTornero/rl-baselines/issues"

[project.scripts]
rl-runner = "rl_baselines.cli.launch:app"

# Hatchling configuration
[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/Readme.md",
]

[tool.hatch.build.targets.wheel]
packages = ["src/rl_baselines"]

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pandas-stubs>=2.3.2.250926",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "ruff>=0.1.6",
    "types-pymysql>=1.1.0.20250916",
    "types-pyyaml>=6.0.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.17",
    "mkdocstrings[python]>=0.30.0",
]
